.TH "test/python Directory Reference" 3 "Tue Aug 8 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test/python Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdemo\&.py\fP"
.br
.ti -1c
.RI "file \fBexample\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmain\&.py\fP"
.br
.ti -1c
.RI "file \fBquery\&.py\fP"
.br
.in -1c
