.TH "pdf-parsing Directory Reference" 3 "Tue Aug 8 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pdf-parsing Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBantenna_usb_rewrite\&.py\fP"
.br
.ti -1c
.RI "file \fBantenna_usb_rewrite_list\&.py\fP"
.br
.ti -1c
.RI "file \fBbook\&.py\fP"
.br
.ti -1c
.RI "file \fBhtmlparser\&.py\fP"
.br
.ti -1c
.RI "file \fBhtmlparser_lists\&.py\fP"
.br
.ti -1c
.RI "file \fBparser\&.py\fP"
.br
.in -1c
