.TH "include Directory Reference" 3 "Fri Sep 1 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBATCABoard\&.hpp\fP"
.br
.RI "\fIDefines the derived \fBATCABoard\fP class\&. \fP"
.ti -1c
.RI "file \fBBoard\&.hpp\fP"
.br
.RI "\fIDefines the base \fBBoard\fP class\&. \fP"
.ti -1c
.RI "file \fBCOMETestBoard\&.hpp\fP"
.br
.ti -1c
.RI "file \fBCouchDB\&.hpp\fP"
.br
.RI "\fIDefines the \fBCouchDB\fP base class and \fBServer\fP and \fBClient\fP derived classes\&. \fP"
.ti -1c
.RI "file \fBdiagnostics\&.hpp\fP"
.br
.ti -1c
.RI "file \fBI2C\&.hpp\fP"
.br
.ti -1c
.RI "file \fBI2C_base\&.hpp\fP"
.br
.ti -1c
.RI "file \fBI2C_define\&.hpp\fP"
.br
.ti -1c
.RI "file \fBI2CBus\&.hpp\fP"
.br
.RI "\fIDefines the \fBI2CBus\fP class\&. \fP"
.ti -1c
.RI "file \fBI2CDevice\&.hpp\fP"
.br
.ti -1c
.RI "file \fBI2CRaw\&.hpp\fP"
.br
.RI "\fIDefines the \fBI2CRaw\fP class\&. \fP"
.ti -1c
.RI "file \fBI2CRegister\&.hpp\fP"
.br
.ti -1c
.RI "file \fBjson\&.hpp\fP"
.br
.ti -1c
.RI "file \fBlibI2C\&.hpp\fP"
.br
.RI "\fIHeader file for Python binding library\&. \fP"
.ti -1c
.RI "file \fBmain\&.hpp\fP"
.br
.ti -1c
.RI "file \fBparser\&.hpp\fP"
.br
.ti -1c
.RI "file \fBunits_define\&.hpp\fP"
.br
.RI "\fIType definitons for units_variant\&. \fP"
.ti -1c
.RI "file \fBupdate\&.hpp\fP"
.br
.in -1c
