.TH "antenna_usb_rewrite" 3 "Tue Aug 8 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
antenna_usb_rewrite \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCp2130\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBusb_to_spi\fP = \fBCp2130\fP()"
.br
.ti -1c
.RI "\fBbook\fP = json\&.load(f_json)"
.br
.ti -1c
.RI "\fBreg\fP = usb_to_spi\&.readBCM53134M(page=int(page), offset=int(\fBbook\fP[page]['addresses'][address]['offset']), length=int(\fBbook\fP[page]['addresses'][address]['word\-length']))"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "antenna_usb_rewrite\&.book = json\&.load(f_json)"

.PP
Definition at line 194 of file antenna_usb_rewrite\&.py\&.
.SS "antenna_usb_rewrite\&.reg = usb_to_spi\&.readBCM53134M(page=int(page), offset=int(\fBbook\fP[page]['addresses'][address]['offset']), length=int(\fBbook\fP[page]['addresses'][address]['word\-length']))"

.PP
Definition at line 198 of file antenna_usb_rewrite\&.py\&.
.SS "antenna_usb_rewrite\&.usb_to_spi = \fBCp2130\fP()"

.PP
Definition at line 189 of file antenna_usb_rewrite\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for COM-Express I2C Stack from the source code\&.
