.TH "include/ATCABoard.hpp" 3 "Tue Aug 8 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/ATCABoard.hpp \- Defines the derived \fBATCABoard\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Board\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBATCABoard\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines the derived \fBATCABoard\fP class\&. 


.PP
\fBAuthor:\fP
.RS 4
David Monk - Imperial College London 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition in file \fBATCABoard\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for COM-Express I2C Stack from the source code\&.
