.TH "include/Board.hpp" 3 "Fri Sep 1 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Board.hpp \- Defines the base \fBBoard\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'I2CBus\&.hpp'\fP
.br
\fC#include 'parser\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBToString\fP"
.br
.ti -1c
.RI "class \fBBoard\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines the base \fBBoard\fP class\&. 


.PP
\fBAuthor:\fP
.RS 4
David Monk - Imperial College London 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition in file \fBBoard\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for COM-Express I2C Stack from the source code\&.
