.TH "book.Address" 3 "Tue Aug 8 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
book.Address \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBoffset\fP, \fBbits\fP, \fBdescription\fP)"
.br
.ti -1c
.RI "def \fBgetBits\fP (self, lines)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBoffset\fP"
.br
.ti -1c
.RI "\fBbits\fP"
.br
.ti -1c
.RI "\fBdescription\fP"
.br
.ti -1c
.RI "\fBtables\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "list \fBbits\fP = []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file book\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def book\&.Address\&.__init__ ( self,  offset,  bits,  description)"

.PP
Definition at line 32 of file book\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def book\&.Address\&.getBits ( self,  lines)"

.PP
Definition at line 36 of file book\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "list book\&.Address\&.bits = []\fC [static]\fP"

.PP
Definition at line 31 of file book\&.py\&.
.SS "book\&.Address\&.bits"

.PP
Definition at line 34 of file book\&.py\&.
.SS "book\&.Address\&.description"

.PP
Definition at line 35 of file book\&.py\&.
.SS "book\&.Address\&.offset"

.PP
Definition at line 33 of file book\&.py\&.
.SS "book\&.Address\&.tables"

.PP
Definition at line 38 of file book\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for COM-Express I2C Stack from the source code\&.
