.TH "book.Bit" 3 "Tue Aug 8 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
book.Bit \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBbit\fP, \fBname\fP, rw, \fBdescription\fP, \fBdefault\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBbit\fP"
.br
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBdescription\fP"
.br
.ti -1c
.RI "\fBdefault\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 23 of file book\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def book\&.Bit\&.__init__ ( self,  bit,  name,  rw,  description,  default)"

.PP
Definition at line 24 of file book\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "book\&.Bit\&.bit"

.PP
Definition at line 25 of file book\&.py\&.
.SS "book\&.Bit\&.default"

.PP
Definition at line 28 of file book\&.py\&.
.SS "book\&.Bit\&.description"

.PP
Definition at line 27 of file book\&.py\&.
.SS "book\&.Bit\&.name"

.PP
Definition at line 26 of file book\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for COM-Express I2C Stack from the source code\&.
