.TH "book.Page" 3 "Tue Aug 8 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
book.Page \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBnumber\fP, \fBdescription\fP)"
.br
.ti -1c
.RI "def \fBgetAddresses\fP (self, lines)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnumber\fP"
.br
.ti -1c
.RI "\fBdescription\fP"
.br
.ti -1c
.RI "\fBaddresses\fP"
.br
.ti -1c
.RI "\fBtables\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "list \fBaddresses\fP = []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 64 of file book\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def book\&.Page\&.__init__ ( self,  number,  description)"

.PP
Definition at line 66 of file book\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def book\&.Page\&.getAddresses ( self,  lines)"

.PP
Definition at line 69 of file book\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "list book\&.Page\&.addresses = []\fC [static]\fP"

.PP
Definition at line 65 of file book\&.py\&.
.SS "book\&.Page\&.addresses"

.PP
Definition at line 70 of file book\&.py\&.
.SS "book\&.Page\&.description"

.PP
Definition at line 68 of file book\&.py\&.
.SS "book\&.Page\&.number"

.PP
Definition at line 67 of file book\&.py\&.
.SS "book\&.Page\&.tables"

.PP
Definition at line 71 of file book\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for COM-Express I2C Stack from the source code\&.
