.TH "pdf-parsing/book.py" 3 "Tue Aug 8 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pdf-parsing/book.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbook\&.Bit\fP"
.br
.ti -1c
.RI "class \fBbook\&.Address\fP"
.br
.ti -1c
.RI "class \fBbook\&.Page\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBbook\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBbook\&.isNumber\fP (x)"
.br
.ti -1c
.RI "def \fBbook\&.isHex\fP (x)"
.br
.ti -1c
.RI "def \fBbook\&.findHex\fP (line)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for COM-Express I2C Stack from the source code\&.
