.TH "book" 3 "Tue Aug 8 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
book \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAddress\fP"
.br
.ti -1c
.RI "class \fBBit\fP"
.br
.ti -1c
.RI "class \fBPage\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBisNumber\fP (x)"
.br
.ti -1c
.RI "def \fBisHex\fP (x)"
.br
.ti -1c
.RI "def \fBfindHex\fP (line)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def book\&.findHex ( line)"

.PP
Definition at line 19 of file book\&.py\&.
.SS "def book\&.isHex ( x)"

.PP
Definition at line 12 of file book\&.py\&.
.SS "def book\&.isNumber ( x)"

.PP
Definition at line 1 of file book\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for COM-Express I2C Stack from the source code\&.
