.TH "boost::units::base_unit_info< test::meter_base_unit >" 3 "Tue Aug 8 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
boost::units::base_unit_info< test::meter_base_unit > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <test_system\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::string \fBname\fP ()"
.br
.ti -1c
.RI "static std::string \fBsymbol\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<>
.br
struct boost::units::base_unit_info< test::meter_base_unit >"

.PP
Definition at line 84 of file test_system\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "static std::string boost::units::base_unit_info< \fBtest::meter_base_unit\fP >::name ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 86 of file test_system\&.hpp\&.
.SS "static std::string boost::units::base_unit_info< \fBtest::meter_base_unit\fP >::symbol ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 87 of file test_system\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for COM-Express I2C Stack from the source code\&.
