.TH "boost::units::test::second_base_unit" 3 "Tue Aug 8 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
boost::units::test::second_base_unit \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <test_system\&.hpp>\fP
.PP
Inherits base_unit< second_base_unit, time_dimension, 3 >\&.
.SH "Detailed Description"
.PP 
Definition at line 48 of file test_system\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for COM-Express I2C Stack from the source code\&.
