.TH "boost::units::test" 3 "Tue Aug 8 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
boost::units::test \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBkilogram_base_unit\fP"
.br
.ti -1c
.RI "struct \fBmeter_base_unit\fP"
.br
.ti -1c
.RI "struct \fBsecond_base_unit\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef make_system< \fBmeter_base_unit\fP, \fBkilogram_base_unit\fP, \fBsecond_base_unit\fP >::type \fBmks_system\fP"
.br
.ti -1c
.RI "typedef unit< dimensionless_type, \fBmks_system\fP > \fBdimensionless\fP"
.br
.RI "\fIunit typedefs \fP"
.ti -1c
.RI "typedef unit< \fBlength_dimension\fP, \fBmks_system\fP > \fBlength\fP"
.br
.ti -1c
.RI "typedef unit< \fBmass_dimension\fP, \fBmks_system\fP > \fBmass\fP"
.br
.ti -1c
.RI "typedef unit< \fBtime_dimension\fP, \fBmks_system\fP > \fBtime\fP"
.br
.ti -1c
.RI "typedef unit< \fBarea_dimension\fP, \fBmks_system\fP > \fBarea\fP"
.br
.ti -1c
.RI "typedef unit< \fBenergy_dimension\fP, \fBmks_system\fP > \fBenergy\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_UNITS_STATIC_CONSTANT\fP (meter, \fBlength\fP)"
.br
.RI "\fIunit constants \fP"
.ti -1c
.RI "\fBBOOST_UNITS_STATIC_CONSTANT\fP (meters, \fBlength\fP)"
.br
.ti -1c
.RI "\fBBOOST_UNITS_STATIC_CONSTANT\fP (kilogram, \fBmass\fP)"
.br
.ti -1c
.RI "\fBBOOST_UNITS_STATIC_CONSTANT\fP (kilograms, \fBmass\fP)"
.br
.ti -1c
.RI "\fBBOOST_UNITS_STATIC_CONSTANT\fP (second, \fBtime\fP)"
.br
.ti -1c
.RI "\fBBOOST_UNITS_STATIC_CONSTANT\fP (seconds, \fBtime\fP)"
.br
.ti -1c
.RI "\fBBOOST_UNITS_STATIC_CONSTANT\fP (square_meter, \fBarea\fP)"
.br
.ti -1c
.RI "\fBBOOST_UNITS_STATIC_CONSTANT\fP (square_meters, \fBarea\fP)"
.br
.ti -1c
.RI "\fBBOOST_UNITS_STATIC_CONSTANT\fP (joule, \fBenergy\fP)"
.br
.ti -1c
.RI "\fBBOOST_UNITS_STATIC_CONSTANT\fP (joules, \fBenergy\fP)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef unit<\fBarea_dimension\fP,\fBmks_system\fP> \fBboost::units::test::area\fP"

.PP
Definition at line 62 of file test_system\&.hpp\&.
.SS "typedef unit<dimensionless_type,\fBmks_system\fP> \fBboost::units::test::dimensionless\fP"

.PP
unit typedefs 
.PP
Definition at line 56 of file test_system\&.hpp\&.
.SS "typedef unit<\fBenergy_dimension\fP,\fBmks_system\fP> \fBboost::units::test::energy\fP"

.PP
Definition at line 63 of file test_system\&.hpp\&.
.SS "typedef unit<\fBlength_dimension\fP,\fBmks_system\fP> \fBboost::units::test::length\fP"

.PP
Definition at line 58 of file test_system\&.hpp\&.
.SS "typedef unit<\fBmass_dimension\fP,\fBmks_system\fP> \fBboost::units::test::mass\fP"

.PP
Definition at line 59 of file test_system\&.hpp\&.
.SS "typedef make_system< \fBmeter_base_unit\fP, \fBkilogram_base_unit\fP, \fBsecond_base_unit\fP>::type \fBboost::units::test::mks_system\fP"

.PP
Definition at line 53 of file test_system\&.hpp\&.
.SS "typedef unit<\fBtime_dimension\fP,\fBmks_system\fP> \fBboost::units::test::time\fP"

.PP
Definition at line 60 of file test_system\&.hpp\&.
.SH "Function Documentation"
.PP 
.SS "boost::units::test::BOOST_UNITS_STATIC_CONSTANT (meter, \fBlength\fP)"

.PP
unit constants 
.SS "boost::units::test::BOOST_UNITS_STATIC_CONSTANT (meters, \fBlength\fP)"

.SS "boost::units::test::BOOST_UNITS_STATIC_CONSTANT (kilogram, \fBmass\fP)"

.SS "boost::units::test::BOOST_UNITS_STATIC_CONSTANT (kilograms, \fBmass\fP)"

.SS "boost::units::test::BOOST_UNITS_STATIC_CONSTANT (second, \fBtime\fP)"

.SS "boost::units::test::BOOST_UNITS_STATIC_CONSTANT (seconds, \fBtime\fP)"

.SS "boost::units::test::BOOST_UNITS_STATIC_CONSTANT (square_meter, \fBarea\fP)"

.SS "boost::units::test::BOOST_UNITS_STATIC_CONSTANT (square_meters, \fBarea\fP)"

.SS "boost::units::test::BOOST_UNITS_STATIC_CONSTANT (joule, \fBenergy\fP)"

.SS "boost::units::test::BOOST_UNITS_STATIC_CONSTANT (joules, \fBenergy\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for COM-Express I2C Stack from the source code\&.
