.TH "Client" 3 "Fri Sep 1 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Client \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CouchDB\&.hpp>\fP
.PP
Inherits \fBCouchDB\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClient\fP (void)"
.br
.RI "\fIClass constructor\&. \fP"
.ti -1c
.RI "\fBClient\fP (std::string url_)"
.br
.RI "\fIClass constructor\&. \fP"
.ti -1c
.RI "\fB~Client\fP (void)"
.br
.RI "\fIClass destructor\&. \fP"
.ti -1c
.RI "std::vector< std::string > \fBgetDatabases\fP (void)"
.br
.RI "\fIGet list of databases on server\&. \fP"
.ti -1c
.RI "void \fBsetDatabase\fP (std::string db)"
.br
.RI "\fISet ID of database to work with\&. \fP"
.ti -1c
.RI "void \fBuploadDocument\fP (\fBjson\fP data)"
.br
.RI "\fIUpload document to database\&. \fP"
.ti -1c
.RI "void \fBuploadDocument\fP (std::string url_, \fBjson\fP data)"
.br
.RI "\fIUpload document to database\&. \fP"
.ti -1c
.RI "void \fBpushDatabase\fP (void)"
.br
.RI "\fIReplicate database to master server\&. \fP"
.ti -1c
.RI "void \fBpushDatabase\fP (\fBjson\fP params)"
.br
.RI "\fIReplicate database to master server with specific parameters\&. \fP"
.ti -1c
.RI "std::string \fBgetDocument\fP (std::string doc)"
.br
.RI "\fIUpload document to database\&. \fP"
.ti -1c
.RI "std::vector< std::pair< std::string, std::string > > \fBgetDocumentIDs\fP (void)"
.br
.RI "\fIGet document IDs and revision IDs for given database\&. \fP"
.ti -1c
.RI "bool \fBcheckOnline\fP (std::string url_)"
.br
.RI "\fICheck if server is online\&. \fP"
.ti -1c
.RI "void \fBdeleteDocument\fP (std::string ID, std::string rev)"
.br
.RI "\fIDelete document from database\&. \fP"
.ti -1c
.RI "void \fBcompactDatabase\fP (void)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 31 of file CouchDB\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Client::Client (void)"

.PP
Class constructor\&. 
.PP
Definition at line 133 of file CouchDB\&.cpp\&.
.SS "Client::Client (std::string url_)"

.PP
Class constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIurl_\fP - URL of \fBCouchDB\fP server\&. 
.RE
.PP

.PP
Definition at line 143 of file CouchDB\&.cpp\&.
.SS "Client::~Client (void)"

.PP
Class destructor\&. 
.PP
Definition at line 152 of file CouchDB\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool Client::checkOnline (std::string url_)"

.PP
Check if server is online\&. 
.PP
\fBParameters:\fP
.RS 4
\fIurl_\fP - URL of server to check\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
True if online, false if not\&. 
.RE
.PP

.PP
Definition at line 251 of file CouchDB\&.cpp\&.
.SS "void Client::compactDatabase (void)"
Compact database to save space on local machine\&. 
.PP
Definition at line 269 of file CouchDB\&.cpp\&.
.SS "void Client::deleteDocument (std::string ID, std::string rev)"

.PP
Delete document from database\&. 
.PP
\fBParameters:\fP
.RS 4
\fIID\fP - ID of document\&. 
.br
\fIrev\fP - revision of document\&. 
.RE
.PP

.PP
Definition at line 261 of file CouchDB\&.cpp\&.
.SS "std::vector< std::string > Client::getDatabases (void)"

.PP
Get list of databases on server\&. 
.PP
\fBReturns:\fP
.RS 4
Vector of strings of IDs of each database\&. 
.RE
.PP

.PP
Definition at line 158 of file CouchDB\&.cpp\&.
.SS "std::string Client::getDocument (std::string doc)"

.PP
Upload document to database\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdoc\fP - Document ID\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
String representation of JSON output\&. 
.RE
.PP

.PP
Definition at line 224 of file CouchDB\&.cpp\&.
.SS "std::vector< std::pair< std::string, std::string > > Client::getDocumentIDs (void)"

.PP
Get document IDs and revision IDs for given database\&. 
.PP
\fBReturns:\fP
.RS 4
Vector of string pairs for ID and revision\&. 
.RE
.PP

.PP
Definition at line 235 of file CouchDB\&.cpp\&.
.SS "void Client::pushDatabase (void)"

.PP
Replicate database to master server\&. 
.PP
Definition at line 200 of file CouchDB\&.cpp\&.
.SS "void Client::pushDatabase (\fBjson\fP params)"

.PP
Replicate database to master server with specific parameters\&. 
.PP
\fBParameters:\fP
.RS 4
\fIparams\fP - JSON key-value pairs for filter function\&. 
.RE
.PP

.PP
Definition at line 211 of file CouchDB\&.cpp\&.
.SS "void Client::setDatabase (std::string db)"

.PP
Set ID of database to work with\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdb\fP - Database ID\&. 
.RE
.PP

.PP
Definition at line 172 of file CouchDB\&.cpp\&.
.SS "void Client::uploadDocument (\fBjson\fP data)"

.PP
Upload document to database\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdata\fP - JSON table to upload\&. 
.RE
.PP

.PP
Definition at line 180 of file CouchDB\&.cpp\&.
.SS "void Client::uploadDocument (std::string url_, \fBjson\fP data)"

.PP
Upload document to database\&. 
.PP
\fBParameters:\fP
.RS 4
\fIurl_\fP - URL of database to upload to\&. 
.br
\fIdata\fP - JSON table to upload\&. 
.RE
.PP

.PP
Definition at line 192 of file CouchDB\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for COM-Express I2C Stack from the source code\&.
