.TH "CouchDB" 3 "Fri Sep 1 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CouchDB \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CouchDB\&.hpp>\fP
.PP
Inherited by \fBClient\fP, and \fBServer\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "bool \fBHTTPGET\fP (std::string url_, std::string *ret)"
.br
.RI "\fIHTTP GET function\&. \fP"
.ti -1c
.RI "bool \fBHTTPPUT\fP (std::string url_, std::string data)"
.br
.RI "\fIHTTP PUT function\&. \fP"
.ti -1c
.RI "bool \fBHTTPPOST\fP (std::string url_, std::string data)"
.br
.RI "\fIHTTP POST function\&. \fP"
.ti -1c
.RI "bool \fBHTTPDELETE\fP (std::string url_)"
.br
.RI "\fIHTTP DELETE function\&. \fP"
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static size_t \fBCallbackFunc\fP (void *contents, size_t size, size_t nmemb, std::string *s)"
.br
.RI "\fICallback function for curl HTTP calls\&. Sends output into string\&. Should not be called outside of CURLOPT_WRITEFUNCTION\&. \fP"
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::string \fBurl\fP"
.br
.ti -1c
.RI "std::string \fBdatabase\fP"
.br
.ti -1c
.RI "\fBjson\fP \fBconfig\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file CouchDB\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "size_t CouchDB::CallbackFunc (void * contents, size_t size, size_t nmemb, std::string * s)\fC [static]\fP, \fC [protected]\fP"

.PP
Callback function for curl HTTP calls\&. Sends output into string\&. Should not be called outside of CURLOPT_WRITEFUNCTION\&. 
.PP
Definition at line 13 of file CouchDB\&.cpp\&.
.SS "bool CouchDB::HTTPDELETE (std::string url_)\fC [protected]\fP"

.PP
HTTP DELETE function\&. 
.PP
\fBParameters:\fP
.RS 4
\fIurl_\fP - URL of file to delete\&. 
.RE
.PP

.PP
Definition at line 110 of file CouchDB\&.cpp\&.
.SS "bool CouchDB::HTTPGET (std::string url_, std::string * ret)\fC [protected]\fP"

.PP
HTTP GET function\&. 
.PP
\fBParameters:\fP
.RS 4
\fIurl_\fP - URL to get from\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
String of output from call\&. 
.RE
.PP

.PP
Definition at line 31 of file CouchDB\&.cpp\&.
.SS "bool CouchDB::HTTPPOST (std::string url_, std::string data)\fC [protected]\fP"

.PP
HTTP POST function\&. 
.PP
\fBParameters:\fP
.RS 4
\fIurl_\fP - URL to post data\&. 
.br
\fIdata\fP - Data to be posted into file\&. 
.RE
.PP

.PP
Definition at line 80 of file CouchDB\&.cpp\&.
.SS "bool CouchDB::HTTPPUT (std::string url_, std::string data)\fC [protected]\fP"

.PP
HTTP PUT function\&. 
.PP
\fBParameters:\fP
.RS 4
\fIurl_\fP - URL to put data\&. 
.br
\fIdata\fP - Data to be put into file\&. 
.RE
.PP

.PP
Definition at line 54 of file CouchDB\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBjson\fP CouchDB::config\fC [protected]\fP"

.PP
Definition at line 23 of file CouchDB\&.hpp\&.
.SS "std::string CouchDB::database\fC [protected]\fP"

.PP
Definition at line 22 of file CouchDB\&.hpp\&.
.SS "std::string CouchDB::url\fC [protected]\fP"

.PP
Definition at line 21 of file CouchDB\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for COM-Express I2C Stack from the source code\&.
