.TH "include/CouchDB.hpp" 3 "Tue Aug 8 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/CouchDB.hpp \- Defines the \fBCouchDB\fP base class and \fBServer\fP and \fBClient\fP derived classes\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <curl/curl\&.h>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <utility>\fP
.br
\fC#include 'json\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCouchDB\fP"
.br
.ti -1c
.RI "class \fBClient\fP"
.br
.ti -1c
.RI "class \fBServer\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBjson\fP = \fBnlohmann::json\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines the \fBCouchDB\fP base class and \fBServer\fP and \fBClient\fP derived classes\&. 


.PP
\fBAuthor:\fP
.RS 4
David Monk - Imperial College London 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition in file \fBCouchDB\&.hpp\fP\&.
.SH "Typedef Documentation"
.PP 
.SS "using \fBjson\fP =  \fBnlohmann::json\fP"

.PP
Definition at line 17 of file CouchDB\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for COM-Express I2C Stack from the source code\&.
