.TH "test/python/demo.py" 3 "Tue Aug 8 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test/python/demo.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBdemo\&.Ui_Dialog\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBdemo\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBdemo\&.app\fP = QtGui\&.QApplication(sys\&.argv)"
.br
.ti -1c
.RI "\fBdemo\&.Dialog\fP = QtGui\&.QDialog()"
.br
.ti -1c
.RI "\fBdemo\&.ui\fP = Ui_Dialog()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for COM-Express I2C Stack from the source code\&.
