.TH "demo" 3 "Tue Aug 8 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
demo \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBUi_Dialog\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBapp\fP = QtGui\&.QApplication(sys\&.argv)"
.br
.ti -1c
.RI "\fBDialog\fP = QtGui\&.QDialog()"
.br
.ti -1c
.RI "\fBui\fP = \fBUi_Dialog\fP()"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "demo\&.app = QtGui\&.QApplication(sys\&.argv)"

.PP
Definition at line 49 of file demo\&.py\&.
.SS "demo\&.Dialog = QtGui\&.QDialog()"

.PP
Definition at line 50 of file demo\&.py\&.
.SS "demo\&.ui = \fBUi_Dialog\fP()"

.PP
Definition at line 51 of file demo\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for COM-Express I2C Stack from the source code\&.
