.TH "demo.Ui_Dialog" 3 "Tue Aug 8 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
demo.Ui_Dialog \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBsetupUi\fP (self, \fBDialog\fP)"
.br
.ti -1c
.RI "def \fBretranslateUi\fP (self, \fBDialog\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBbuttonBox\fP"
.br
.ti -1c
.RI "\fBlistView\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file demo\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def demo\&.Ui_Dialog\&.retranslateUi ( self,  Dialog)"

.PP
Definition at line 43 of file demo\&.py\&.
.SS "def demo\&.Ui_Dialog\&.setupUi ( self,  Dialog)"

.PP
Definition at line 26 of file demo\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "demo\&.Ui_Dialog\&.buttonBox"

.PP
Definition at line 29 of file demo\&.py\&.
.SS "demo\&.Ui_Dialog\&.listView"

.PP
Definition at line 34 of file demo\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for COM-Express I2C Stack from the source code\&.
