.TH "devices.Device" 3 "Tue Aug 8 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
devices.Device \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBaddress\fP, \fBproperties\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBproperties\fP"
.br
.ti -1c
.RI "\fBaddress\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file devices\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def devices\&.Device\&.__init__ ( self,  address,  properties)"

.PP
Definition at line 4 of file devices\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "devices\&.Device\&.address"

.PP
Definition at line 6 of file devices\&.py\&.
.SS "devices\&.Device\&.properties"

.PP
Definition at line 5 of file devices\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for COM-Express I2C Stack from the source code\&.
