.TH "test/python/example.cpp" 3 "Tue Aug 8 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test/python/example.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <pybind11/pybind11\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBoard\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBPYBIND11_PLUGIN\fP (example)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "PYBIND11_PLUGIN (example)"

.PP
Definition at line 17 of file example\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for COM-Express I2C Stack from the source code\&.
