.TH "pdf-parsing/htmlparser_lists.py" 3 "Tue Aug 8 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pdf-parsing/htmlparser_lists.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBhtmlparser_lists\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBhtmlparser_lists\&.isHex\fP (x)"
.br
.ti -1c
.RI "def \fBhtmlparser_lists\&.getRange\fP (number)"
.br
.ti -1c
.RI "def \fBhtmlparser_lists\&.generatePageList\fP ()"
.br
.ti -1c
.RI "def \fBhtmlparser_lists\&.getPageOffsetNumbers\fP (div)"
.br
.ti -1c
.RI "def \fBhtmlparser_lists\&.getAddressName\fP (div)"
.br
.ti -1c
.RI "def \fBhtmlparser_lists\&.getDescription\fP (div)"
.br
.ti -1c
.RI "def \fBhtmlparser_lists\&.getWordLength\fP (div)"
.br
.ti -1c
.RI "def \fBhtmlparser_lists\&.getBits\fP (div)"
.br
.ti -1c
.RI "def \fBhtmlparser_lists\&.main\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for COM-Express I2C Stack from the source code\&.
