.TH "htmlparser" 3 "Tue Aug 8 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
htmlparser \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBisHex\fP (x)"
.br
.ti -1c
.RI "def \fBgetRange\fP (number)"
.br
.ti -1c
.RI "def \fBgeneratePageList\fP ()"
.br
.ti -1c
.RI "def \fBgetPageOffsetNumbers\fP (div)"
.br
.ti -1c
.RI "def \fBgetAddressName\fP (div)"
.br
.ti -1c
.RI "def \fBgetDescription\fP (div)"
.br
.ti -1c
.RI "def \fBgetWordLength\fP (div)"
.br
.ti -1c
.RI "def \fBgetBits\fP (div)"
.br
.ti -1c
.RI "def \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def htmlparser\&.generatePageList ()"

.PP
Definition at line 16 of file htmlparser\&.py\&.
.SS "def htmlparser\&.getAddressName ( div)"

.PP
Definition at line 62 of file htmlparser\&.py\&.
.SS "def htmlparser\&.getBits ( div)"

.PP
Definition at line 79 of file htmlparser\&.py\&.
.SS "def htmlparser\&.getDescription ( div)"

.PP
Definition at line 65 of file htmlparser\&.py\&.
.SS "def htmlparser\&.getPageOffsetNumbers ( div)"

.PP
Definition at line 53 of file htmlparser\&.py\&.
.SS "def htmlparser\&.getRange ( number)"

.PP
Definition at line 11 of file htmlparser\&.py\&.
.SS "def htmlparser\&.getWordLength ( div)"

.PP
Definition at line 71 of file htmlparser\&.py\&.
.SS "def htmlparser\&.isHex ( x)"

.PP
Definition at line 4 of file htmlparser\&.py\&.
.SS "def htmlparser\&.main (void)"

.PP
Definition at line 105 of file htmlparser\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for COM-Express I2C Stack from the source code\&.
