.TH "pdf-parsing/htmlparser.py" 3 "Tue Aug 8 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pdf-parsing/htmlparser.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBhtmlparser\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBhtmlparser\&.isHex\fP (x)"
.br
.ti -1c
.RI "def \fBhtmlparser\&.getRange\fP (number)"
.br
.ti -1c
.RI "def \fBhtmlparser\&.generatePageList\fP ()"
.br
.ti -1c
.RI "def \fBhtmlparser\&.getPageOffsetNumbers\fP (div)"
.br
.ti -1c
.RI "def \fBhtmlparser\&.getAddressName\fP (div)"
.br
.ti -1c
.RI "def \fBhtmlparser\&.getDescription\fP (div)"
.br
.ti -1c
.RI "def \fBhtmlparser\&.getWordLength\fP (div)"
.br
.ti -1c
.RI "def \fBhtmlparser\&.getBits\fP (div)"
.br
.ti -1c
.RI "def \fBhtmlparser\&.main\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for COM-Express I2C Stack from the source code\&.
