.TH "include/I2C_define.hpp" 3 "Tue Aug 8 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/I2C_define.hpp \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDS3232_ADDR\fP   0b11010000"
.br
.ti -1c
.RI "#define \fBPCICLOCK_ADDR\fP   0xD8"
.br
.ti -1c
.RI "#define \fBATCA_ARBITER\fP   0xE0"
.br
.ti -1c
.RI "#define \fBATCA_FANOUT\fP   0xE4"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ATCA_ARBITER   0xE0"

.PP
Definition at line 17 of file I2C_define\&.hpp\&.
.SS "#define ATCA_FANOUT   0xE4"

.PP
Definition at line 18 of file I2C_define\&.hpp\&.
.SS "#define DS3232_ADDR   0b11010000"
I2C_define\&.h Purpose: useful definitions\&. 
.PP
\fBAuthor:\fP
.RS 4
David Monk - Imperial College London 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition at line 12 of file I2C_define\&.hpp\&.
.SS "#define PCICLOCK_ADDR   0xD8"

.PP
Definition at line 16 of file I2C_define\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for COM-Express I2C Stack from the source code\&.
