.TH "include/I2CDevice.hpp" 3 "Fri Sep 1 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/I2CDevice.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'I2CRegister\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBI2CDevice\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::unordered_map< std::string, \fBI2CBaseRegister\fP * > \fBregister_map\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef std::unordered_map<std::string, \fBI2CBaseRegister\fP*> \fBregister_map\fP"

.PP
Definition at line 15 of file I2CDevice\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for COM-Express I2C Stack from the source code\&.
