.TH "src/I2CRegister.cpp" 3 "Fri Sep 1 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/I2CRegister.cpp \- Defines functions for the derived \fBI2CBaseRegister\fP classes\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'I2CRegister\&.hpp'\fP
.br

.SH "Detailed Description"
.PP 
Defines functions for the derived \fBI2CBaseRegister\fP classes\&. 


.PP
\fBAuthor:\fP
.RS 4
David Monk - Imperial College London 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition in file \fBI2CRegister\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for COM-Express I2C Stack from the source code\&.
