.TH "I2CRaw" 3 "Tue Aug 8 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
I2CRaw \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <I2CRaw\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBI2CRaw\fP (void)"
.br
.ti -1c
.RI "\fB~I2CRaw\fP ()"
.br
.ti -1c
.RI "int \fBread\fP (uint32_t address, uint32_t start_point)"
.br
.ti -1c
.RI "void \fBwrite\fP (uint32_t address, uint8_t buffer, uint32_t start_point)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file I2CRaw\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "I2CRaw::I2CRaw (void)"

.PP
Definition at line 3 of file I2CRaw\&.cpp\&.
.SS "I2CRaw::~I2CRaw ()"

.PP
Definition at line 9 of file I2CRaw\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "int I2CRaw::read (uint32_t address, uint32_t start_point)"

.PP
Definition at line 43 of file I2CRaw\&.cpp\&.
.SS "void I2CRaw::write (uint32_t address, uint8_t buffer, uint32_t start_point)"

.PP
Definition at line 48 of file I2CRaw\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for COM-Express I2C Stack from the source code\&.
