.TH "include/I2CRegister.hpp" 3 "Fri Sep 1 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/I2CRegister.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <unordered_map>\fP
.br
\fC#include <functional>\fP
.br
\fC#include 'I2C\&.hpp'\fP
.br
\fC#include 'units_define\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBI2CBaseRegister\fP"
.br
.ti -1c
.RI "class \fBGenericI2CRegister\fP"
.br
.ti -1c
.RI "class \fBTimeI2CRegister\fP"
.br
.ti -1c
.RI "class \fBDS3232TemperatureI2CRegister\fP"
.br
.ti -1c
.RI "class \fBPCIClockPLLModeRegister\fP"
.br
.ti -1c
.RI "class \fBPCIClockOutputEnableRegister\fP"
.br
.ti -1c
.RI "class \fBInternalRegister\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for COM-Express I2C Stack from the source code\&.
