.TH "include/libI2C.hpp" 3 "Tue Aug 8 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/libI2C.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <pybind11/pybind11\&.h>\fP
.br
\fC#include <pybind11/stl\&.h>\fP
.br
\fC#include 'ATCABoard\&.hpp'\fP
.br
\fC#include 'COMETestBoard\&.hpp'\fP
.br
\fC#include 'I2CRaw\&.hpp'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for COM-Express I2C Stack from the source code\&.
