.TH "libsrc/libI2C.cpp" 3 "Tue Aug 8 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libsrc/libI2C.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'libI2C\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBPYBIND11_PLUGIN\fP (libI2C)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "PYBIND11_PLUGIN (libI2C)"

.PP
Definition at line 3 of file libI2C\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for COM-Express I2C Stack from the source code\&.
