.TH "include/libI2C.hpp" 3 "Fri Sep 1 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/libI2C.hpp \- Header file for Python binding library\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <pybind11/pybind11\&.h>\fP
.br
\fC#include <pybind11/stl\&.h>\fP
.br
\fC#include 'ATCABoard\&.hpp'\fP
.br
\fC#include 'COMETestBoard\&.hpp'\fP
.br
\fC#include 'I2CRaw\&.hpp'\fP
.br

.SH "Detailed Description"
.PP 
Header file for Python binding library\&. 


.PP
\fBAuthor:\fP
.RS 4
David Monk - Imperial College London 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition in file \fBlibI2C\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for COM-Express I2C Stack from the source code\&.
