.TH "include/main.hpp" 3 "Fri Sep 1 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/main.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <thread>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include 'update\&.hpp'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSLEEP_TIME\fP   2"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SLEEP_TIME   2"
\fBmain\&.hpp\fP Purpose: main header file\&. 
.PP
\fBAuthor:\fP
.RS 4
David Monk - Imperial College London 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition at line 17 of file main\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for COM-Express I2C Stack from the source code\&.
