.TH "multiply" 3 "Tue Aug 8 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multiply \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits static_visitor<>\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmultiply\fP (double aDouble)"
.br
.ti -1c
.RI "template<typename T > void \fBoperator()\fP (T &operand)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBunits_variant\fP \fBmRet\fP"
.br
.ti -1c
.RI "double \fBmDouble\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 75 of file test\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "multiply::multiply (double aDouble)\fC [inline]\fP"

.PP
Definition at line 80 of file test\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > void multiply::operator() (T & operand)\fC [inline]\fP"

.PP
Definition at line 82 of file test\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "double multiply::mDouble"

.PP
Definition at line 78 of file test\&.cpp\&.
.SS "\fBunits_variant\fP multiply::mRet"

.PP
Definition at line 77 of file test\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for COM-Express I2C Stack from the source code\&.
