.TH "nlohmann::detail::merge_and_renumber< index_sequence< I1... >, index_sequence< I2... > >" 3 "Tue Aug 8 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nlohmann::detail::merge_and_renumber< index_sequence< I1... >, index_sequence< I2... > > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json\&.hpp>\fP
.PP
Inherits \fBnlohmann::detail::index_sequence< I1\&.\&.\&.,(sizeof\&.\&.\&.(I1)+I2)\&.\&.\&. >\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<std::size_t\&.\&.\&. I1, std::size_t\&.\&.\&. I2>
.br
struct nlohmann::detail::merge_and_renumber< index_sequence< I1\&.\&.\&. >, index_sequence< I2\&.\&.\&. > >"

.PP
Definition at line 509 of file json\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for COM-Express I2C Stack from the source code\&.
