.TH "nlohmann::detail::to_json_fn" 3 "Tue Aug 8 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nlohmann::detail::to_json_fn \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename BasicJsonType , typename T > void \fBoperator()\fP (BasicJsonType &j, T &&val) const noexcept(noexcept(std::declval< \fBto_json_fn\fP >()\&.call(j, std::forward< T >(val), \fBpriority_tag\fP< 1 >{})))"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1226 of file json\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename BasicJsonType , typename T > void nlohmann::detail::to_json_fn::operator() (BasicJsonType & j, T && val) const\fC [inline]\fP, \fC [noexcept]\fP"

.PP
Definition at line 1245 of file json\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for COM-Express I2C Stack from the source code\&.
