.TH "nlohmann::detail::priority_tag< N >" 3 "Tue Aug 8 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nlohmann::detail::priority_tag< N > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json\&.hpp>\fP
.SH "Detailed Description"
.PP 

.SS "template<unsigned N>
.br
struct nlohmann::detail::priority_tag< N >"

.PP
Definition at line 546 of file json\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for COM-Express I2C Stack from the source code\&.
