.TH "nlohmann::detail::is_compatible_array_type< BasicJsonType, CompatibleArrayType >" 3 "Tue Aug 8 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nlohmann::detail::is_compatible_array_type< BasicJsonType, CompatibleArrayType > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json\&.hpp>\fP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static auto constexpr \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class BasicJsonType, class CompatibleArrayType>
.br
struct nlohmann::detail::is_compatible_array_type< BasicJsonType, CompatibleArrayType >"

.PP
Definition at line 768 of file json\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "template<class BasicJsonType , class CompatibleArrayType > auto constexpr \fBnlohmann::detail::is_compatible_array_type\fP< BasicJsonType, CompatibleArrayType >::value\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
=
        conjunction<negation<std::is_same<void, CompatibleArrayType>>,
        negation<is_compatible_object_type<
        BasicJsonType, CompatibleArrayType>>,
        negation<std::is_constructible<typename BasicJsonType::string_t,
        CompatibleArrayType>>,
        negation<is_basic_json_nested_type<BasicJsonType, CompatibleArrayType>>,
        has_value_type<CompatibleArrayType>,
        has_iterator<CompatibleArrayType>>::value
.fi
.PP
Definition at line 770 of file json\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for COM-Express I2C Stack from the source code\&.
