.TH "test/pcigen.h" 3 "Tue Aug 8 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test/pcigen.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include 'I2C\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPCIGen\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for COM-Express I2C Stack from the source code\&.
