.TH "Server" 3 "Fri Sep 1 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Server \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CouchDB\&.hpp>\fP
.PP
Inherits \fBCouchDB\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBServer\fP (void)"
.br
.RI "\fIClass constructor\&. \fP"
.ti -1c
.RI "\fB~Server\fP (void)"
.br
.RI "\fIClass destructor\&. \fP"
.ti -1c
.RI "void \fBeditConfig\fP (std::string bus, std::string device, std::string property, std::string value)"
.br
.RI "\fIEdit config entry for all slaves\&. \fP"
.ti -1c
.RI "void \fBeditConfig\fP (std::string board, std::string bus, std::string device, std::string property, std::string value)"
.br
.RI "\fIEdit config entry for specific board\&. \fP"
.ti -1c
.RI "void \fBpushDatabase\fP (\fBjson\fP \fBdatabase\fP)"
.br
.RI "\fIPush config database to slave\&. \fP"
.ti -1c
.RI "void \fBpushChanges\fP (void)"
.br
.RI "\fIPush config databases to slaves\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 49 of file CouchDB\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Server::Server (void)"

.PP
Class constructor\&. 
.PP
Definition at line 277 of file CouchDB\&.cpp\&.
.SS "Server::~Server (void)"

.PP
Class destructor\&. 
.PP
Definition at line 287 of file CouchDB\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void Server::editConfig (std::string bus, std::string device, std::string property, std::string value)"

.PP
Edit config entry for all slaves\&. 
.PP
\fBParameters:\fP
.RS 4
\fIbus\fP - Bus of property\&. 
.br
\fIdevice\fP - Device of property\&. 
.br
\fIproperty\fP - Property ID\&. 
.br
\fIvalue\fP - Value to be written\&. 
.RE
.PP

.PP
Definition at line 296 of file CouchDB\&.cpp\&.
.SS "void Server::editConfig (std::string board, std::string bus, std::string device, std::string property, std::string value)"

.PP
Edit config entry for specific board\&. 
.PP
\fBParameters:\fP
.RS 4
\fIbus\fP - Bus of property\&. 
.br
\fIdevice\fP - Device of property\&. 
.br
\fIproperty\fP - Property ID\&. 
.br
\fIvalue\fP - Value to be written\&. 
.RE
.PP

.PP
Definition at line 314 of file CouchDB\&.cpp\&.
.SS "void Server::pushChanges (void)"

.PP
Push config databases to slaves\&. 
.PP
Definition at line 340 of file CouchDB\&.cpp\&.
.SS "void Server::pushDatabase (\fBjson\fP database)"

.PP
Push config database to slave\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdatabase\fP - JSON of metadat for database to psush to\&. 
.RE
.PP

.PP
Definition at line 327 of file CouchDB\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for COM-Express I2C Stack from the source code\&.
