.TH "src/Si53106Registers.cpp" 3 "Tue Aug 8 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Si53106Registers.cpp \- Defines functions for the derived classes specific to the Si53106 component\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'I2CRegister\&.hpp'\fP
.br

.SH "Detailed Description"
.PP 
Defines functions for the derived classes specific to the Si53106 component\&. 


.PP
\fBAuthor:\fP
.RS 4
David Monk - Imperial College London 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition in file \fBSi53106Registers\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for COM-Express I2C Stack from the source code\&.
