.TH "static" 3 "Tue Aug 8 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
static \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBsendFlag\fP (data, metadata)"
.br
.ti -1c
.RI "def \fBgetData\fP ()"
.br
.ti -1c
.RI "def \fBupdateServer\fP ()"
.br
.ti -1c
.RI "def \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def static\&.getData ()"

.PP
Definition at line 19 of file static\&.py\&.
.SS "def static\&.main (void)"

.PP
Definition at line 68 of file static\&.py\&.
.SS "def static\&.sendFlag ( data,  metadata)"

.PP
Definition at line 7 of file static\&.py\&.
.SS "def static\&.updateServer ()"

.PP
Definition at line 55 of file static\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for COM-Express I2C Stack from the source code\&.
