.TH "std::less<::nlohmann::detail::value_t >" 3 "Fri Sep 1 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::less<::nlohmann::detail::value_t > \- specialization for std::less<value_t>  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (\fBnlohmann::detail::value_t\fP lhs, \fBnlohmann::detail::value_t\fP rhs) const noexcept"
.br
.RI "\fIcompare two value_t enum values \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<>
.br
struct std::less<::nlohmann::detail::value_t >"
specialization for std::less<value_t> 
.PP
Definition at line 14495 of file json\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool std::less<::\fBnlohmann::detail::value_t\fP >::operator() (\fBnlohmann::detail::value_t\fP lhs, \fBnlohmann::detail::value_t\fP rhs) const\fC [inline]\fP, \fC [noexcept]\fP"

.PP
compare two value_t enum values 
.PP
\fBSince:\fP
.RS 4
version 3\&.0\&.0 
.RE
.PP

.PP
Definition at line 14501 of file json\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for COM-Express I2C Stack from the source code\&.
