.TH "Test" 3 "Tue Aug 8 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Test \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTest\fP (int x)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 136 of file test\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Test::Test (int x)\fC [inline]\fP"

.PP
Definition at line 138 of file test\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for COM-Express I2C Stack from the source code\&.
