.TH "Update" 3 "Fri Sep 1 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Update \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <update\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUpdate\fP (\fBI2C_base\fP *i2c)"
.br
.RI "\fIClass constructor\&. \fP"
.ti -1c
.RI "\fB~Update\fP (void)"
.br
.RI "\fIClass destructor\&. \fP"
.ti -1c
.RI "void \fBsaveActive\fP (void)"
.br
.RI "\fISave active registers to local cache and then push the database to an external server\&. \fP"
.ti -1c
.RI "void \fBsaveStatic\fP (void)"
.br
.RI "\fISave static registers to local cache and then push the database to an external server\&. \fP"
.ti -1c
.RI "void \fBpurgeDatabase\fP (void)"
.br
.RI "\fIPurge database of any entries over an hour old\&. \fP"
.ti -1c
.RI "void \fBgetConfig\fP (void)"
.br
.RI "\fICheck if config files have changed and update registers if true\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file update\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Update::Update (\fBI2C_base\fP * i2c)"

.PP
Class constructor\&. 
.PP
Definition at line 13 of file update\&.cpp\&.
.SS "Update::~Update (void)"

.PP
Class destructor\&. 
.PP
Definition at line 22 of file update\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void Update::getConfig (void)"

.PP
Check if config files have changed and update registers if true\&. 
.PP
Definition at line 156 of file update\&.cpp\&.
.SS "void Update::purgeDatabase (void)"

.PP
Purge database of any entries over an hour old\&. 
.PP
Definition at line 116 of file update\&.cpp\&.
.SS "void Update::saveActive (void)"

.PP
Save active registers to local cache and then push the database to an external server\&. 
.PP
Definition at line 29 of file update\&.cpp\&.
.SS "void Update::saveStatic (void)"

.PP
Save static registers to local cache and then push the database to an external server\&. 
.PP
Definition at line 60 of file update\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for COM-Express I2C Stack from the source code\&.
