.TH "include/update.hpp" 3 "Fri Sep 1 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/update.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'CouchDB\&.hpp'\fP
.br
\fC#include 'ATCABoard\&.hpp'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <ctime>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <unordered_map>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <boost/filesystem\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBUpdate\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for COM-Express I2C Stack from the source code\&.
