.TH "bin/update.py" 3 "Tue Aug 8 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bin/update.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBupdate\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBupdate\&.getData\fP ()"
.br
.ti -1c
.RI "def \fBupdate\&.updateServer\fP ()"
.br
.ti -1c
.RI "def \fBupdate\&.main\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for COM-Express I2C Stack from the source code\&.
