.TH "update" 3 "Tue Aug 8 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
update \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBgetData\fP ()"
.br
.ti -1c
.RI "def \fBupdateServer\fP ()"
.br
.ti -1c
.RI "def \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def update\&.getData ()"

.PP
Definition at line 7 of file update\&.py\&.
.SS "def update\&.main (void)"

.PP
Definition at line 43 of file update\&.py\&.
.SS "def update\&.updateServer ()"

.PP
Definition at line 30 of file update\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for COM-Express I2C Stack from the source code\&.
