.TH "Update" 3 "Tue Aug 8 2017" "Version 1.0" "COM-Express I2C Stack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Update \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <update\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUpdate\fP (void)"
.br
.ti -1c
.RI "\fB~Update\fP (void)"
.br
.ti -1c
.RI "void \fBsaveActive\fP (void)"
.br
.ti -1c
.RI "void \fBsaveStatic\fP (void)"
.br
.ti -1c
.RI "void \fBpurgeDatabase\fP (void)"
.br
.ti -1c
.RI "void \fBgetConfig\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file update\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Update::Update (void)"

.PP
Definition at line 3 of file update\&.cpp\&.
.SS "Update::~Update (void)"

.PP
Definition at line 9 of file update\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void Update::getConfig (void)"

.PP
Definition at line 140 of file update\&.cpp\&.
.SS "void Update::purgeDatabase (void)"

.PP
Definition at line 101 of file update\&.cpp\&.
.SS "void Update::saveActive (void)"

.PP
Definition at line 13 of file update\&.cpp\&.
.SS "void Update::saveStatic (void)"

.PP
Definition at line 44 of file update\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for COM-Express I2C Stack from the source code\&.
